language: go

go:
#  - 1.0 This won't work with coveralls
#  - 1.1 This won't work with coveralls
#  - 1.2 This won't work with our XML wonderfulness
  - 1.3
  - 1.4
  - 1.5
  - tip

before_install:
  - go get -u -v github.com/axw/gocov/gocov
  - go get -u -v github.com/mattn/goveralls
  - go get -u -v github.com/golang/lint/golint

script:
  - diff -u <(echo -n) <(gofmt -s -d ./)
  - diff -u <(echo -n) <(go vet ./...)
  - diff -u <(echo -n) <(golint ./...)
  - go test -v -race -covermode=atomic -coverprofile=coverage.out

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
